### PR TITLE
py3 port: Fix `exception Exception, e` syntax and port `print` to functions

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by akien-mga** [comment]
I wanted to make a separate PR for the second commit but since they would conflict with each other, I put both in here.

**Comment by akien-mga** [comment]
My bad, I forgot to check pending PRs and @strycore's #2 (hey :)) already handles those.

**Comment by akien-mga** [comment]
Reopening as #2 does not handle all the files fixed in this PR. I can rebase it after #2 is merged.

**Comment by Ryochan7** [comment]
I resolved the conflicts on my end and got the changes merged. Thank you for the changes.

**Pull request merged**
