### PR TITLE
Various fixes for Python3, allows adding Xbox pad

### PR DESCRIPTION
**Pull request by strycore**
I went through a few parts of the code to allow adding a XBox 360 controller. The controller isn't picked up by the daemon yet but I haven't worked on that part yet.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I only use sc-controller with the Steam Controller so supporting other controllers wasn't a concern. I can try out these changes with my DS4 as see how that goes.

**Comment by strycore** [comment]
I'll do a rebase of my branch since you already merged PR #1 and there was some overlap in my changes.

**Comment by Ryochan7** [comment]
With your initial changes, getting DS4 support working again only required a couple of additional changes. DPad mapping did not work still but it does not work when using vanilla 0.4.7 in Python 2.7.17 either.

I tried Xbox 360 controller support as well. The registration window mapped the controller properly but the main GUI fell into a weird recursion problem. I haven't tried it in vanilla sc-controller yet.

**Comment by akien-mga** [comment]
Looking forward to a rebase of this one, beyond the Xbox pad support it fixes py3-incompatible which also prevents me from using the current `python3` branch for my Steam Controller (bytecompiling fails when packaging the scripts with py2-only code).

**Comment by akien-mga** [comment]
@strycore FYI, seems your patch missed one occurrence of `except Exception, e`:
```diff
diff --git a/scc/osd/inputdisplay.py b/scc/osd/inputdisplay.py
index fb60aa97..e3e7c926 100644
--- a/scc/osd/inputdisplay.py
+++ b/scc/osd/inputdisplay.py
@@ -141,7 +141,7 @@ class InputDisplay(OSDWindow):
                                else:
                                        self.hilights[self.OBSERVE_COLOR].remove(what)
                                self._update_background()
-                       except KeyError, e:
+                       except KeyError as e:
                                # Non fatal
                                pass
                else:
```

**Comment by Ryochan7** [comment]
I finally tried this scenario on Xubuntu 19.10 running Python 2.7.17. The same recursion issues pop up there as well when attempting to map an Xbox 360 controller. At least Python 3 is not a factor in that problem.

**Comment by Ryochan7** [comment]
Got the changes merged in and I added a couple of my own. I don't know if I will end up using a DS4 in sc-controller but at least it works as well as it did before. Thank you for contributing these changes.

**Comment by strycore** [comment]
Thanks! I'll do more testing on my side. Might also run the project through Pylint and Black but that might result in huge PRs, are you ok with that?

**Comment by akien-mga** [comment]
> Might also run the project through Pylint and Black but that might result in huge PRs, are you ok with that?

I would advise against doing style and linter changes, unless @Ryochan7 is willing to make this a full-fledged continuation fork not meant to be rebased on the original project, or eventually PR'ed upstream.

**Comment by strycore** [comment]
The upstream seems to be going into a different direction with the C port. SC Controller contains a lot of python code that would help lutris a lot if there was closer integration with both project, but for that SC-Controller and Lutris have to run on the same Python version.
If that can make the maintenance work easier for @Ryochan7 , I can create a fork in the Lutris org and assign a few maintainers. I don't really want to start shipping releases of SC-Controller but it's also a really good piece of software that doesn't run on current distros so if that's needed, we'll likely use the lutris PPA to ship packages for 20.04.

**Comment by Ryochan7** [comment]
I have started using pyflakes to catch some problems with the code. Only some minor testing has been done but that program found a few unresolved errors with the code already. I might test out Pylint and see what changes it suggests but I don't think I would commit those changes to the repo.

I do not want to hard fork the project unless there are some changes that require doing so. This fork is meant to be a maintenance release while the C version is being developed. The main purpose of this fork is for me to be able to play some games in my Linux backlog. So far, Layers of Fear is the one "game" completed using sc-controller as the mapper. Pier Solar is next on the list.

**Comment by akien-mga** [comment]
After thinking about it some more, I think a hard fork for the python 3 version might not be a bad option if several of us are willing to co-maintain it. It doesn't have to be an aggressive fork, and it can eventually be phased out if/when the C version is ready for production. This maintenance fork wouldn't do feature development beyond making sure that things work with Python 3 as well as they did with Python 2.

The C version is still in development, but it still doesn't have any GUI. The GUI it uses is the same Python 2-based on as the Python backend.

And now the Steam Controller has been discontinued by Valve, so the interest in sc-controller will likely dwindle, both from users and developers. I'm in the same boat of wanting to play some non-Steam games with my Steam Controller on a Python 3-only distro, so I have interest in having a reference Python 3 port of sc-controller that I can use. I guess @strycore / Lutris' use case is similar.

**Comment by strycore** [comment]
Let's see if that C port get released... Also, what good will this rewrite be good for if it still uses a Python 2 GUI?

Btw, this is not a fork, it's continuation of the existing project. The fork is the C rewrite. My goal is only to have the current version of SC-Controller in Python 3, nothing more. I don't want to bring in additional features. As I've mentioned before, this project has a lot of code related to joystick input and this could be really valuable for Lutris. But to be of any use, the project has to be in a clean and fully functional state for current systems.

**Comment by Ryochan7** [comment]
I don't know if you are paying attention to the issue on the Kozec repo but there is now a functioning (at least for me) AppImage for the Python 3 port if you would like to test it. The AppImage version has been tested on Fedora 32, Manjaro 20.0.3, and Xubuntu 19.10.

SC_Controller-x86_64_20200613.AppImage
https://drive.google.com/file/d/1l4I_Rnt092e2Zfqw_edLFcZtm54g9jpo/view?usp=sharing

**Comment by strycore** [comment]
I have tried the AppImage and it does not work.

**Pull request merged**
