### PR TITLE
Fix all tests

### PR DESCRIPTION
**Pull request by rnhmjoj**
Fix the tests after changes related to the VDF parser and remainders.
Take a look at the commit messages for more explanations.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I have never run any of the test suite. Maybe I should but it has not been a big deal to me. Anyway, the changes look good and have been merged in. Thank you for the changes.

**Comment by rnhmjoj** [comment]
> I have never run any of the test suite.

Yeah, I figured. The python builder in Nixpkgs runs tests by default, so that's why I'm insisting with these.
Would it be possible to make a new release with the tests working?

**Comment by Ryochan7** [comment]
Got a new release out now. There was one small change that had to be made to fix the test suite on my Fedora box.

https://github.com/Ryochan7/sc-controller/releases/tag/v0.4.8.6

**Comment by rnhmjoj** [comment]
Great! Thank you.

**Pull request merged**
