### PR TITLE
fixed BT support for Python3

### PR DESCRIPTION
**Pull request by clst**
Hi,

I could not live any longer with the USB cable and fixed the BT support.

It had two issues on my Arch system since I think updating kernel >= 5

BT-hardware addresses seems to be in lowercase now (sometimes)  
and scc/drivers/sc_by_bt.py was not quite ready for Python3 yet after getting that one fixed.

Would you like to take a look? Can you verify if yours works as well? Or if it worked without those changes?

### CODE REVIEW

**Comment by Ryochan7** [comment]
Sorry about the delay. Been busy trying to decipher the DualSense controller. I will have to give this a try later. I thought I had tested normal BT support at some point but I could be mistaken. Normally I played wired but I sometimes use the SC dongle.

**Comment by clst** [comment]
no big deal. My day job keeps me busy more than I'd like too. I've been using it a few days now and it works well.

Two other problems have come up but I don't think they are BT related: the overlay showing current binds doesn't work/is blank. And starting programs via the OSD seems to crash.

**Comment by Ryochan7** [comment]
Checked out the code and BT support now works. Thank you for the update.

I don't think I have ever used that functionality in the overlay. Looks like that is something else I will have to test on my end and figure out a fix.

**Comment by Ryochan7** [comment]
Got the current bindings window fixed with commit 39690b388b618794dd04f091669e81c6d42086b6. The Run Program portion of the OSD worked for me as is.

**Pull request merged**
